fish: update plugin config

diff --git a/.config/fish/conf.d/bin/git-forgit b/.config/fish/conf.d/bin/git-forgit
--- a/.config/fish/conf.d/bin/git-forgit
+++ b/.config/fish/conf.d/bin/git-forgit
@@ -12,31 +12,7 @@
 # This gives users the choice to set aliases inside of their git config instead
 # of their shell config if they prefer.
 
-# Check if fzf is installed
-installed_fzf_version=$(fzf --version 2>/dev/null | awk '{print $1}')
-if [[ -z "$installed_fzf_version" ]]; then
-    echo "fzf is not installed. Please install fzf first."
-    exit 1
-fi
-
-# Check fzf version
-required_fzf_version="0.49.0"
-higher_fzf_version=$(printf '%s\n' "$required_fzf_version" "$installed_fzf_version" | sort -V | tail -n1)
-if [[ "$higher_fzf_version" != "$installed_fzf_version" ]]; then
-    echo "fzf version $required_fzf_version or higher is required. You have $installed_fzf_version."
-    exit 1
-fi
-
-# Set shell for fzf preview commands
-# Disable shellcheck for "which", because it suggests "command -v xxx" instead,
-# which is not a working replacement.
-# See https://github.com/koalaman/shellcheck/issues/1162
-# shellcheck disable=2230
-SHELL="$(which bash)"
-export SHELL
-
-# Get absolute forgit path
-FORGIT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)/$(basename -- "${BASH_SOURCE[0]}")
+REQUIRED_FZF_VERSION="0.49.0"
 
 FORGIT_FZF_DEFAULT_OPTS="
 $FZF_DEFAULT_OPTS
@@ -194,14 +170,14 @@ _forgit_log_preview() {
     local sha
     sha=$(echo "$1" | _forgit_extract_sha)
     shift
-    echo "$sha" | xargs -I% git show --color=always -U"$_forgit_preview_context" % -- "$@" | _forgit_pager show
+    git show --color=always -U"$_forgit_preview_context" "${sha}" -- "$@" | _forgit_pager show
 }
 
 _forgit_log_enter() {
     local sha
     sha=$(echo "$1" | _forgit_extract_sha)
     shift
-    echo "$sha" | xargs -I% "${FORGIT}" show % "$@"
+    "${FORGIT}" show "${sha}" "$@"
 }
 
 # git commit viewer
@@ -256,6 +232,14 @@ _forgit_reflog() {
     return $fzf_exit_code
 }
 
+_forgit_remove_status_from_diff_line() {
+    # Remove the status prefix from a diff line, e.g.
+    #   [M]     somefile
+    # becomes
+    #   somefile
+    sed 's/^[[:space:]]*\[[A-Z0-9]*\][[:space:]]*//'
+}
+
 _forgit_get_files_from_diff_line() {
     # Construct a null-terminated list of the filenames
     # The input looks like one of these lines:
@@ -268,13 +252,13 @@ _forgit_get_files_from_diff_line() {
     #   oldfile\0
     # We have to do a two-step sed -> tr pipe because OSX's sed implementation does
     # not support the null-character directly.
-    sed 's/^[[:space:]]*\[[A-Z0-9]*\][[:space:]]*//' | sed 's/  ->  /\n/' | tr '\n' '\0'
+    _forgit_remove_status_from_diff_line | sed 's/  ->  /\n/' | tr '\n' '\0'
 }
 
 _forgit_get_single_file_from_diff_line() {
     # Similar to the function above, but only gets a single file from a single line
     # Gets the new name of renamed files
-    sed 's/^[[:space:]]*\[[A-Z0-9]*\][[:space:]]*//' | sed 's/.*->  //'
+    _forgit_remove_status_from_diff_line | sed 's/.*->  //'
 }
 
 _forgit_exec_diff() {
@@ -434,6 +418,10 @@ _forgit_show() {
 
 _forgit_add_preview() {
     file=$(echo "$1" | _forgit_get_single_file_from_add_line)
+    # $file can be a directory when status.showUntrackedFiles is explicitly set to 'normal'
+    # In this case, show the content of the directory and return
+    [ -d "$file" ] && eval "$_forgit_dir_view \"$file\"" && return 0
+
     if (git status -s -- "$file" | grep '^??') &>/dev/null; then  # diff with /dev/null for untracked files
         git diff --color=always --no-index -- /dev/null "$file" | _forgit_pager diff | sed '2 s/added:/untracked:/'
     else
@@ -464,9 +452,9 @@ _forgit_edit_add_file() {
 # git add selector
 _forgit_add() {
     _forgit_inside_work_tree || return 1
-    local changed unmerged untracked files opts
+    local changed unmerged untracked files opts show_untracked
     # Add files if passed as arguments
-    [[ $# -ne 0 ]] && { _forgit_git_add "$@" && git status -s; return $?; }
+    _forgit_contains_non_flags "$@" && { _forgit_git_add "$@" && git status -s; return $?; }
 
     changed=$(git config --get-color color.status.changed red)
     unmerged=$(git config --get-color color.status.unmerged red)
@@ -479,14 +467,15 @@ _forgit_add() {
         $FORGIT_ADD_FZF_OPTS
     "
     files=()
+    show_untracked=$(git config status.showUntrackedFiles)
     while IFS='' read -r file; do
         files+=("$file")
-    done < <(git -c color.status=always -c status.relativePaths=true -c core.quotePath=false status -su |
+    done < <(git -c color.status=always -c status.relativePaths=true -c core.quotePath=false status -s --untracked="${show_untracked:-all}" |
         grep -F -e "$changed" -e "$unmerged" -e "$untracked" |
         sed -E 's/^(..[^[:space:]]*)[[:space:]]+(.*)$/[\1]  \2/' |
         FZF_DEFAULT_OPTS="$opts" fzf |
         _forgit_get_single_file_from_add_line)
-    [[ "${#files[@]}" -gt 0 ]] && _forgit_git_add "${files[@]}" && git status -s && return
+    [[ "${#files[@]}" -gt 0 ]] && _forgit_git_add "$@" "${files[@]}" && git status -s && return
     echo 'Nothing to add.'
 }
 
@@ -529,24 +518,26 @@ _forgit_reset_head() {
 
 _forgit_stash_show_preview() {
     local stash
-    stash=$(echo "$1" | cut -d: -f1)
-    _forgit_git_stash_show "$stash" | _forgit_pager diff
+    stash=$(echo "$1" | _forgit_extract_stash_name)
+    git show --color=always -U"$_forgit_preview_context" "${stash}" | _forgit_pager show
 }
 
-_forgit_git_stash_show() {
-    git stash show --color=always --ext-diff "$@"
+_forgit_stash_show_enter() {
+    local stash
+    stash=$(echo "$1" | _forgit_extract_stash_name)
+    "${FORGIT}" show "${stash}"
 }
 
 # git stash viewer
 _forgit_stash_show() {
     _forgit_inside_work_tree || return 1
     local opts
-    [[ $# -ne 0 ]] && { _forgit_git_stash_show "$@"; return $?; }
+    [[ $# -ne 0 ]] && { "${FORGIT}" show "$@"; return $?; }
     _forgit_stash_show_git_opts=()
     _forgit_parse_array _forgit_stash_show_git_opts "$FORGIT_STASH_SHOW_GIT_OPTS"
     opts="
         $FORGIT_FZF_DEFAULT_OPTS
-        +s +m -0 --tiebreak=index --bind=\"enter:execute($FORGIT stash_show_preview {} | $FORGIT pager enter)\"
+        +s +m -0 --tiebreak=index --bind=\"enter:execute($FORGIT stash_show_enter {})\"
         --bind=\"ctrl-y:execute-silent($FORGIT yank_stash_name {})\"
         --preview=\"$FORGIT stash_show_preview {}\"
         $FORGIT_STASH_FZF_OPTS
@@ -637,7 +628,9 @@ _forgit_clean() {
 }
 
 _forgit_cherry_pick_preview() {
-    echo "$1" | cut -f2- | _forgit_extract_sha | xargs -I% git show --color=always % | _forgit_pager show
+    local sha
+    sha=$(echo "$1" | cut -f2- | _forgit_extract_sha)
+    git show --color=always "${sha}" | _forgit_pager show
 }
 
 _forgit_cherry_pick() {
@@ -753,31 +746,73 @@ _forgit_file_preview() {
     local sha
     sha=$(echo "$1" | _forgit_extract_sha)
     shift
-    echo "$sha" | xargs -I% git show --color=always % -- "$@" | _forgit_pager show
+    git show --color=always "${sha}" -- "$@" | _forgit_pager show
 }
 
 _forgit_fixup() {
     _forgit_inside_work_tree || return 1
     git diff --cached --quiet && echo 'Nothing to fixup: there are no staged changes.' && return 1
-    local opts graph quoted_files target_commit prev_commit
+    _forgit_edit_commit --fixup "$FORGIT_FIXUP_FZF_OPTS" "$FORGIT_FIXUP_GIT_OPTS" "$@"
+}
+
+_forgit_squash() {
+    _forgit_inside_work_tree || return 1
+    git diff --cached --quiet && echo 'Nothing to squash: there are no staged changes.' && return 1
+    _forgit_edit_commit --squash "$FORGIT_SQUASH_FZF_OPTS" "$FORGIT_SQUASH_GIT_OPTS" "$@"
+}
+
+_forgit_edit_commit() {
+    local action fzf_opts opts graph quoted_files target_commit prev_commit
+    action=$1
+    fzf_opts=$2
     graph=()
     [[ $_forgit_log_graph_enable == true ]] && graph=(--graph)
-    _forgit_fixup_git_opts=()
-    _forgit_parse_array _forgit_fixup_git_opts "$FORGIT_FIXUP_GIT_OPTS"
+    git_opts=()
+    _forgit_parse_array git_opts "$3"
+    shift 3
     quoted_files=$(_forgit_quote_files "$@")
     opts="
         $FORGIT_FZF_DEFAULT_OPTS
         +s +m --tiebreak=index
         --bind=\"ctrl-y:execute-silent($FORGIT yank_sha {})\"
         --preview=\"$FORGIT file_preview {} $quoted_files\"
-        $FORGIT_FIXUP_FZF_OPTS
+        $fzf_opts
     "
     target_commit=$(
         git log "${graph[@]}" --color=always --format="$_forgit_log_format" "$@" |
         _forgit_emojify |
         FZF_DEFAULT_OPTS="$opts" fzf |
         _forgit_extract_sha)
-    if [[ -n "$target_commit" ]] && git commit "${_forgit_fixup_git_opts[@]}" --fixup "$target_commit"; then
+    # GIT_EDITOR=: is needed to skip the editor
+    if [[ -n "$target_commit" ]] && GIT_EDITOR=: git commit "${git_opts[@]}" "$action" "$target_commit"; then
+        prev_commit=$(_forgit_previous_commit "$target_commit")
+        # rebase will fail if there are unstaged changes so --autostash is needed to temporarily stash them
+        # GIT_SEQUENCE_EDITOR=: is needed to skip the editor
+        GIT_SEQUENCE_EDITOR=: git rebase --autostash -i --autosquash "$prev_commit"
+    fi
+}
+
+_forgit_reword() {
+    _forgit_inside_work_tree || return 1
+    local opts graph quoted_files target_commit prev_commit
+    graph=()
+    [[ $_forgit_log_graph_enable == true ]] && graph=(--graph)
+    git_opts=()
+    _forgit_parse_array _forgit_reword_git_opts "$FORGIT_REWORD_GIT_OPTS"
+    quoted_files=$(_forgit_quote_files "$@")
+    opts="
+        $FORGIT_FZF_DEFAULT_OPTS
+        +s +m --tiebreak=index
+        --bind=\"ctrl-y:execute-silent($FORGIT yank_sha {})\"
+        --preview=\"$FORGIT file_preview {} $quoted_files\"
+        $FORGIT_REWORD_FZF_OPTS
+    "
+    target_commit=$(
+        git log "${graph[@]}" --color=always --format="$_forgit_log_format" "$@" |
+        _forgit_emojify |
+        FZF_DEFAULT_OPTS="$opts" fzf |
+        _forgit_extract_sha)
+    if [[ -n "$target_commit" ]] && git commit "${git_opts[@]}" --fixup=reword:"$target_commit"; then
         prev_commit=$(_forgit_previous_commit "$target_commit")
         # rebase will fail if there are unstaged changes so --autostash is needed to temporarily stash them
         # GIT_SEQUENCE_EDITOR=: is needed to skip the editor
@@ -799,7 +834,7 @@ _forgit_git_checkout_file() {
 _forgit_checkout_file() {
     _forgit_inside_work_tree || return 1
     local files opts
-    [[ $# -ne 0 ]] && { _forgit_git_checkout_file -- "$@"; return $?; }
+    _forgit_contains_non_flags "$@" && { _forgit_git_checkout_file "$@"; return $?; }
     opts="
         $FORGIT_FZF_DEFAULT_OPTS
         -m -0
@@ -811,7 +846,7 @@ _forgit_checkout_file() {
         files+=("$file")
     done < <(_forgit_list_files --modified |
         FZF_DEFAULT_OPTS="$opts" fzf)
-    [[ "${#files[@]}" -gt 0 ]] && _forgit_git_checkout_file "${files[@]}"
+    [[ "${#files[@]}" -gt 0 ]] && _forgit_git_checkout_file "$@" "${files[@]}"
 }
 
 _forgit_git_checkout_branch() {
@@ -884,7 +919,9 @@ _forgit_checkout_tag() {
 }
 
 _forgit_checkout_commit_preview() {
-    echo "$1" | _forgit_extract_sha | xargs -I% git show --color=always % | _forgit_pager show
+    local sha
+    sha=$(echo "$1" | _forgit_extract_sha)
+    git show --color=always "${sha}" | _forgit_pager show
 }
 
 _forgit_git_checkout_commit() {
@@ -947,11 +984,9 @@ _forgit_branch_delete() {
 }
 
 _forgit_revert_preview() {
-    echo "$1" |
-    cut -f2- |
-    _forgit_extract_sha |
-    xargs -I% git show --color=always % |
-    _forgit_pager show
+    local sha
+    sha=$(echo "$1" | cut -f2- | _forgit_extract_sha)
+    git show --color=always "${sha}" | _forgit_pager show
 }
 
 _forgit_git_revert() {
@@ -1036,9 +1071,9 @@ _forgit_blame() {
 }
 
 # git ignore generator
-export FORGIT_GI_REPO_REMOTE=${FORGIT_GI_REPO_REMOTE:-https://github.com/dvcs/gitignore}
-export FORGIT_GI_REPO_LOCAL="${FORGIT_GI_REPO_LOCAL:-${XDG_CACHE_HOME:-$HOME/.cache}/forgit/gi/repos/dvcs/gitignore}"
-export FORGIT_GI_TEMPLATES=${FORGIT_GI_TEMPLATES:-$FORGIT_GI_REPO_LOCAL/templates}
+export FORGIT_GI_REPO_REMOTE=${FORGIT_GI_REPO_REMOTE:-https://github.com/github/gitignore}
+export FORGIT_GI_REPO_LOCAL="${FORGIT_GI_REPO_LOCAL:-${XDG_CACHE_HOME:-$HOME/.cache}/forgit/gi/repos/github/gitignore}"
+export FORGIT_GI_TEMPLATES=${FORGIT_GI_TEMPLATES:-$FORGIT_GI_REPO_LOCAL}
 
 _forgit_path_preview() {
     local path name ext pager
@@ -1068,7 +1103,7 @@ _forgit_ignore() {
         args=()
         while IFS='' read -r arg; do
             args+=("$arg")
-        done < <(_forgit_paths_list "$FORGIT_GI_TEMPLATES" .gitignore | 
+        done < <(_forgit_paths_list "$FORGIT_GI_TEMPLATES" .gitignore |
             nl -w4 -s'  ' |
             FZF_DEFAULT_OPTS="$opts" fzf | awk '{print $2}')
     fi
@@ -1138,7 +1173,54 @@ _forgit_paths_list() {
     find "$path" -name "*$ext" -print |sed -e "s#$ext\$##" -e 's#.*/##' -e '/^$/d' | sort -fu
 }
 
-public_commands=(
+check_prequisites() {
+    local installed_fzf_version
+    local higher_fzf_version
+
+    # Check if fzf is installed
+    installed_fzf_version=$(fzf --version 2>/dev/null | awk '{print $1}')
+    if [[ -z "$installed_fzf_version" ]]; then
+        echo "fzf is not installed. Please install fzf first."
+        exit 1
+    fi
+
+    # Check fzf version
+    higher_fzf_version=$(printf '%s\n' "$REQUIRED_FZF_VERSION" "$installed_fzf_version" | sort -V | tail -n1)
+    if [[ "$higher_fzf_version" != "$installed_fzf_version" ]]; then
+        echo "fzf version $REQUIRED_FZF_VERSION or higher is required. You have $installed_fzf_version."
+        exit 1
+    fi
+}
+
+main() {
+    local cmd="$1"
+    shift
+
+    check_prequisites
+
+    # Set shell for fzf preview commands
+    SHELL="$(which bash)"
+    export SHELL
+
+    # Get absolute forgit path
+    FORGIT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)/$(basename -- "${BASH_SOURCE[0]}")
+
+    # shellcheck disable=SC2076
+    if [[ ! " ${PUBLIC_COMMANDS[*]} " =~ " ${cmd} " ]] && [[ ! " ${PRIVATE_COMMANDS[*]} " =~ " ${cmd} " ]]; then
+        if [[ -z "$cmd" ]]; then
+            printf "forgit: missing command\n\n"
+        else
+            printf "forgit: '%s' is not a valid forgit command.\n\n" "$cmd"
+        fi
+        printf "The following commands are supported:\n"
+        printf "\t%s\n" "${PUBLIC_COMMANDS[@]}"
+        exit 1
+    fi
+
+    _forgit_"${cmd}" "$@"
+}
+
+PUBLIC_COMMANDS=(
     "add"
     "attributes"
     "blame"
@@ -1152,6 +1234,8 @@ public_commands=(
     "clean"
     "diff"
     "fixup"
+    "squash"
+    "reword"
     "ignore"
     "log"
     "reflog"
@@ -1163,7 +1247,7 @@ public_commands=(
     "stash_push"
 )
 
-private_commands=(
+PRIVATE_COMMANDS=(
     "add_preview"
     "blame_preview"
     "branch_preview"
@@ -1181,6 +1265,7 @@ private_commands=(
     "show_enter"
     "show_preview"
     "stash_push_preview"
+    "stash_show_enter"
     "stash_show_preview"
     "yank_sha"
     "yank_stash_name"
@@ -1193,19 +1278,10 @@ private_commands=(
     "pager"
 )
 
-cmd="$1"
-shift
-
-# shellcheck disable=SC2076
-if [[ ! " ${public_commands[*]} " =~ " ${cmd} " ]] && [[ ! " ${private_commands[*]} " =~ " ${cmd} " ]]; then
-    if [[ -z "$cmd" ]]; then
-        printf "forgit: missing command\n\n"
-    else
-        printf "forgit: '%s' is not a valid forgit command.\n\n" "$cmd"
-    fi
-    printf "The following commands are supported:\n"
-    printf "\t%s\n" "${public_commands[@]}"
-    exit 1
+# Check if the script is being sourced. This is necessary for unit tests where
+# we do not want to execute the main function.
+if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
+    return 0
 fi
 
-_forgit_"${cmd}" "$@"
+main "${@}"
